```R
df <- read.csv('mlbootcamp5_train.csv')  
head(df)
``` 
OUT:
```R
  id   age gender height weight ap_hi ap_lo cholesterol gluc smoke alco active cardio
1  0 18393      2    168     62   110    80           1    1     0    0      1      0
2  1 20228      1    156     85   140    90           3    1     0    0      1      1
3  2 18857      1    165     64   130    70           3    1     0    0      0      1
4  3 17623      2    169     82   150   100           1    1     0    0      1      1
5  4 17474      1    156     56   100    60           1    1     0    0      0      0
6  8 21914      1    151     67   120    80           2    2     0    0      0      0
```
### 1. Сколько мужчин и женщин представлено в этом наборе данных?    
```R
mean(df$height[df$gender == 1]) 
 161.3556
mean(df$height[df$gender == 2])
169.9479
female <- which(sex == TRUE)  
male <- which(sex == FALSE)
print(length(female))
45530
print(length(male))
24470
```
### 2. Кто в среднем реже указывает, что употребляет алкоголь – мужчины или женщины? 
```R
sex <- as.array(df$gender == 1)  
female <- which(sex == TRUE)  
male <- which(sex == FALSE)  
alco_fem <- length(as.array(which(as.array(df$alco == 1) & sex == TRUE)))  
alco_m <- length(as.array(which(as.array(df$alco == 1) & sex == FALSE)))  
print(alco_fem)
1161
print(alco_m) 
2603
````
### 3.Во сколько раз (округленно, round) процент курящих среди мужчин больше, чем процент курящих среди женщин (по крайней мере, по этим анкетным данным)?
```R
smoke_fem <- length(as.array(which(as.array(df$smoke == 1) & sex == TRUE)))  
smoke_m <- length(as.array(which(as.array(df$smoke == 1) & sex == FALSE)))  
s_w <- smoke_fem / length(female) * 100  
s_m <- smoke_m / length(male) * 100  
print(round(s_m/s_w))
```
OUT:
```R
12
```
### 4.В чём здесь измеряется возраст? На сколько месяцев (примерно) отличаются медианные значения возраста курящих и некурящих? 
```R
df$age_years <- round(df$age / 365)  
head(df)
```
OUT:
```R
  id   age gender height weight ap_hi ap_lo cholesterol gluc smoke alco active cardio age_years
1  0 18393      2    168     62   110    80           1    1     0    0      1      0        50
2  1 20228      1    156     85   140    90           3    1     0    0      1      1        55
3  2 18857      1    165     64   130    70           3    1     0    0      0      1        52
4  3 17623      2    169     82   150   100           1    1     0    0      1      1        48
5  4 17474      1    156     56   100    60           1    1     0    0      0      0        48
6  8 21914      1    151     67   120    80           2    2     0    0      0      0        60
```
```R
mean(df$age_years[df$smoke == 1]) 
```
OUT:
```R
52.29664
```
```R
mean(df$age_years[df$smoke == 0])
```
OUT:
```R
53.43939
```
OUT:
```R  
print(median(df$age_years[df$smoke == 0])*12 - median(df$age_years[df$smoke == 1])*12)
```
OUT:
```R
 24
 ```
### 5.  
1. Создайте новый признак age_years – возраст в годах, округлив до целых (round). Для данного примера отберите курящих мужчин от 60 до 64 лет включительно.  
2. Категории уровня холестрина на рисунке и в наших данных отличаются. Отображение значений на картинке в значения признака  cholesterol следующее: 4 ммоль/л -> 1, 5-7 ммоль/л -> 2, 8 ммоль/л -> 3.  
3. Интересуют 2 подвыборки курящих мужчин возраста от 60 до 64 лет включительно: первая с верхним артериальным давлением строго меньше 120 мм рт.ст. и концентрацией холестерина – 4 ммоль/л, а вторая – с верхним артериальным давлением от 160 (включительно) до 180 мм рт.ст. (не включительно) и концентрацией холестерина – 8 ммоль/л. 
Во сколько раз (округленно, round) отличаются доли больных людей (согласно целевому признаку, cardio) в этих двух подвыборках?
```R
v1 <- df$cardio[(df$gender == 2) & (df$age_years >=60) & (df$age_years <=64) & (df$smoke == 1) & (df$ap_hi < 120) & (df$cholesterol ==1)] 
v2 <- df$cardio[(df$gender == 2) & (df$age_years >=60) & (df$age_years <=64) & (df$smoke == 1) & (df$ap_hi >= 160) &(df$ap_hi < 180) & (df$cholesterol ==1)]
print(round(mean(v2)/mean(v1)))
```
OUT:
```R
3
```
### 6. Постройте новый признак – BMI (Body Mass Index). Для этого надо вес в килограммах поделить на квадрат роста в метрах. Нормальными считаются значения BMI от 18.5 до 25.
   ### Выбрать верные утверждения:  
   ### 1. Медианный BMI по выборке превышает норму.  
   ### 2. У женщин в среднем BMI ниже, чем у мужчин.  
   ### 3. У здоровых в среднем BMI выше, чем у больных.  
   ### 4. В сегменте здоровых и непьющих мужчин в среднем BMI ближе к норме, чем в сегменте здоровых и непьющих женщин.
```R     
df$height_m <- (df$height/100)**2
df$BMI <- df$weight/df$height_m
```
#### 6.1
```R
print(median(round(df$BMI)))
```
OUT:
```R
26
```
#### 6.2
```R
print(mean(round(df$BMI[female])))
```
OUT:27.98043
```R
print(mean(round(df$BMI[male])))
```
OUT:
```R
26.74593
```
### 6.3
```R
print(mean(round(df$BMI[which(df$cardio == 0)])))
```
OUT:
```R
26.54156
```
```R
print(mean(round(df$BMI[which(df$cardio == 1)])))
```
OUT:
```R
28.55742
```
#### 6.4  
```R
print(mean(round(df$BMI[which(as.array(df$alco == 0) & as.array(df$cardio == 0) & sex == FALSE)])))
```
OUT:
```R
25.86425
```
```R
print(mean(round(df$BMI[which(as.array(df$alco == 0) & as.array(df$cardio == 0) & sex == TRUE)])))
``` 
OUT:
```R
26.84032
```
### 7. Отфильтруйте следующие сегменты пациентов (считаем это ошибками в данных):  
 ###  1. Указанное нижнее значение артериального давления строго выше верхнего.  
  ###  2. Рост строго меньше 2.5%-перцентили или строго больше 97.5%-перцентили.
  ### 3. Вес строго меньше 2.5%-перцентили или строго больше 97.5%-перцентили.  
 ###   Сколько процентов данных (округленно, round) мы выбросили? 
 ```R
new_df <- length(df$BMI[(df$ap_hi >=  df$ap_lo) & (df$height >= quantile(df$height, 0.025)) & (df$height <= quantile(df$height, 0.975)) & (df$weight >= quantile(df$weight, 0.025)) & (df$weight <= quantile(df$weight, 0.975))])  
first_df <- length(df$BMI)  
s = round( new_df/ first_df *100, 0)  
print(100-s)  
```
OUT:
```R
10
```
